ARG CPU="arm64"

FROM docker.io/rkrispin/baser-4.4.0:${CPU}-0.0.1

RUN apt-get update && apt-get install -y --no-install-recommends libarchive-dev

COPY setting_files/install_packages.R setting_files/packages.json pkgs/

RUN Rscript pkgs/install_packages.R